sudo: false
language: python
python:
- '3.5'
install:
- pip install -r requirements.txt
script:
- "./scripts/run_smoke_tests.sh"
before_script:
- export DISPLAY=:99.0
- sh -e /etc/init.d/xvfb start
- sleep 5
